### PR TITLE
Updated aias.json with correct magicbytes and protocol

### PR DESCRIPTION
**Pull request by click2install**

### CODE REVIEW

**Comment by ultra-pool** [comment]
added to my fork of this. Thank you for the update conf.

**Comment by sroziewski** [comment]
Hi, How do you know what the magicbytes is?
I need a conf for APR COIN, can you help me?

**Comment by KingricharVD** [comment]
Sorry what do you need?



14:27 - שׁלמא שׁבק אנא לכון שׁלמא דילי יהב אנא לכון לא הוא איכנא דיהב עלמא אנא יהב אנא לכון לא נתדוד לבכון ולא נדחל 

John 14:27 - Peace I leave with you; my peace I give to you. It is not as the world giveth, that I give to you. Let not your heart be troubled, nor be afraid.

**Comment by click2install** [comment]
> Hi, How do you know what the magicbytes is?
> I need a conf for APR COIN, can you help me?

If this is the correct repository for APR then these are the magicbytes
https://github.com/APRCoin/zenith-repository/blob/master/src/chainparams.cpp#L103-L106

```
2e92eca4
```

**Pull request closed without merging**
